# Generated by Django 2.2.6 on 2019-11-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
