# Generated by Django 2.2.6 on 2019-11-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_destination_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
